# Generated by Django 6.0.4 on 2026-04-24 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_distance', models.FloatField()),
                ('total_duration', models.FloatField()),
                ('polyline', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_loc', models.CharField(max_length=255)),
                ('pickup_loc', models.CharField(max_length=255)),
                ('dropoff_loc', models.CharField(max_length=255)),
                ('current_cycle_used', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('image', models.ImageField(upload_to='log_sheets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_sheets', to='logistics_app.routeplan')),
            ],
        ),
        migrations.AddField(
            model_name='routeplan',
            name='trip_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_plans', to='logistics_app.triprequest'),
        ),
    ]
