# Generated by Django 6.0.4 on 2026-04-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogSheet',
        ),
    ]
